"""
png_to_svg.py
-------------
Converts a monochrome logo PNG to a scalable, color-configurable SVG.

Usage:
    python png_to_svg.py [OPTIONS]

Options:
    --input   Path to the source PNG file      (default: logo.png)
    --output  Path for the generated SVG file  (default: logo.svg)
    --color   Fill color for the logo shape    (default: #1a6b35)
    --width   Output SVG width in pixels       (default: 400)
    --height  Output SVG height in pixels      (default: 0, auto)

Examples:
    python png_to_svg.py
    python png_to_svg.py --color "#2d7a4f"
    python png_to_svg.py --input my_logo.png --output my_logo.svg --color "#0055a4" --width 600

Requirements:
    pip install Pillow numpy potrace
"""

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

try:
    import potrace
except ImportError:
    sys.exit(
        "ERROR: 'potrace' is not installed.\n"
        "Run: pip install potrace"
    )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_logo_mask(png_path: Path) -> tuple[np.ndarray, tuple[int, int]]:
    """
    Load a PNG and return a boolean mask of logo pixels plus original dimensions.

    Detection strategy: logo pixels are significantly darker than the
    checkerboard/white background. Works for any single-color logo on a
    light or transparent background.
    """
    img = Image.open(png_path).convert("RGBA")
    arr = np.array(img, dtype=np.uint8)

    # Composite onto white so semi-transparent edges are handled cleanly
    bg = np.ones_like(arr) * 255
    alpha = arr[:, :, 3:4] / 255.0
    rgb = (arr[:, :, :3] * alpha + bg[:, :, :3] * (1 - alpha)).astype(np.uint8)

    # Luminance: pixels much darker than white are logo foreground
    luminance = 0.299 * rgb[:, :, 0] + 0.587 * rgb[:, :, 1] + 0.114 * rgb[:, :, 2]
    mask = luminance < 160  # threshold; adjust if logo is light-colored

    return mask, img.size  # (width, height)


def trace_mask_to_paths(mask: np.ndarray, turdsize: int = 8, opttolerance: float = 0.3):
    """Run potrace on a boolean mask and return the traced Path object."""
    bitmap = potrace.Bitmap(mask)
    return bitmap.trace(turdsize=turdsize, opttolerance=opttolerance)


def pt(p) -> tuple[float, float]:
    """Extract x, y from a potrace _Point (which uses .x/.y, not indexing)."""
    return p.x, p.y


def curve_to_svg_path(curve) -> str:
    """
    Convert a single potrace Curve to an SVG path data string.

    potrace coordinates: origin is bottom-left, Y increases upward.
    SVG coordinates:    origin is top-left,    Y increases downward.
    Flip is handled by the viewBox / transform in the SVG wrapper.
    """
    parts: list[str] = []
    sx, sy = pt(curve.start_point)
    parts.append(f"M {sx:.4f} {sy:.4f}")

    for segment in curve.segments:
        ex, ey = pt(segment.end_point)
        if segment.is_corner:
            cx, cy = pt(segment.c)
            parts.append(f"L {cx:.4f} {cy:.4f} L {ex:.4f} {ey:.4f}")
        else:
            c1x, c1y = pt(segment.c1)
            c2x, c2y = pt(segment.c2)
            parts.append(
                f"C {c1x:.4f} {c1y:.4f} "
                f"{c2x:.4f} {c2y:.4f} "
                f"{ex:.4f} {ey:.4f}"
            )

    parts.append("Z")
    return " ".join(parts)


def build_svg(
    path_obj,
    img_width: int,
    img_height: int,
    color: str,
    out_width: int,
    out_height: int,
) -> str:
    """
    Assemble all potrace curves into a complete SVG document.

    The SVG uses a CSS custom property (--logo-color) so the fill
    can be overridden from a stylesheet or inline style on the <svg> tag.

    Web usage examples:
        /* CSS */
        svg { --logo-color: #0055a4; }

        /* Inline */
        <svg style="--logo-color: #e63946;" ...>

        /* JavaScript */
        document.querySelector('svg').style.setProperty('--logo-color', '#ff6b35');
    """
    all_d: list[str] = []
    for curve in path_obj:
        all_d.append(curve_to_svg_path(curve))

    combined_d = " ".join(all_d)

    # potrace Y is bottom-up; flip with a transform so the logo is right-side-up
    transform = f"scale(1,-1) translate(0,-{img_height})"

    svg = f"""<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by png_to_svg.py
  Color control:
    CSS variable : --logo-color  (set on <svg> or any ancestor)
    Fallback     : {color}

  Override examples:
    <svg style="--logo-color: #0055a4;" ...>
    svg {{ --logo-color: #e63946; }}  /* in your stylesheet */
    document.querySelector('svg').style.setProperty('--logo-color', '#new');
-->
<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="0 0 {img_width} {img_height}"
  width="{out_width}"
  height="{out_height}"
  role="img"
  aria-label="Logo"
>
  <style>
    :root {{
      --logo-color: {color};
    }}
  </style>
  <g transform="{transform}" fill="var(--logo-color, {color})" fill-rule="evenodd">
    <path d="{combined_d}"/>
  </g>
</svg>"""
    return svg


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a monochrome logo PNG to a colorizable SVG.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--input",  default="logo.png",  help="Source PNG file path")
    parser.add_argument("--output", default="logo.svg",  help="Output SVG file path")
    parser.add_argument("--color",  default="#1a6b35",   help="Logo fill color (hex)")
    parser.add_argument("--width",  type=int, default=400, help="SVG output width in px")
    parser.add_argument("--height", type=int, default=0,
                        help="SVG output height in px (0 = auto from aspect ratio)")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        sys.exit(f"ERROR: Input file not found: {input_path}")

    print(f"Loading: {input_path}")
    mask, (img_w, img_h) = load_logo_mask(input_path)
    print(f"  Image size : {img_w} x {img_h} px")
    print(f"  Logo pixels: {mask.sum():,} / {mask.size:,}")

    print("Tracing paths...")
    path_obj = trace_mask_to_paths(mask)
    curves = list(path_obj)
    print(f"  Curves found: {len(curves)}")

    if not curves:
        sys.exit(
            "ERROR: No paths were traced. The logo may be too light or "
            "the threshold needs adjusting (edit load_logo_mask)."
        )

    # Compute output height if not specified
    out_height = args.height if args.height > 0 else round(args.width * img_h / img_w)

    print(f"Building SVG: {args.width} x {out_height} px, color={args.color}")
    svg_content = build_svg(path_obj, img_w, img_h, args.color, args.width, out_height)

    output_path.write_text(svg_content, encoding="utf-8")
    print(f"Saved: {output_path} ({output_path.stat().st_size / 1024:.1f} KB)")
    print()
    print("To change color at runtime:")
    print('  CSS  : svg { --logo-color: #your-color; }')
    print('  JS   : svg.style.setProperty("--logo-color", "#your-color");')
    print('  HTML : <svg style="--logo-color: #your-color;" ...>')


if __name__ == "__main__":
    main()